---
- name: Make sure requirements are met to run vmware modules PyVmoi and PyVim
  ansible.builtin.pip:
    name:
      - PyVmomi
      - PyVim
    state: present
  delegate_to: localhost

- name: Generate random hostname
  ansible.builtin.set_fact:
    random_hostname: "host{{ lookup('community.general.random_string', length=6, chars=['ascii_lowercase', 'digits']) }}"
    domain: "itmco.local"

- name: Set FQDN
  ansible.builtin.set_fact:
    fqdn: "{{ random_hostname }}.{{ domain }}"

- name: Create a virtual machine with customization and DHCP
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    datacenter: "{{ datacenter_name }}"
    cluster: "{{ cluster_name }}"
    name: "{{ vm_name }}"
    template: "{{ 'RH8' if version == '8' else 'RH9' }}"
    folder: "{{ vm_folder }}"
    state: "poweredon"
    customization:
      domain: "{{ domain }}"
      hostname: "{{ random_hostname }}"
    networks:
      - name: "{{ vm_network_name }}"
        device_type: vmxnet3
        connected: true
        start_connected: true
    wait_for_ip_address: true
  delegate_to: localhost
  register: vm_creation_result

- name: Get VM MoID
  community.vmware.vmware_vm_info:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    vm_name: "{{ vm_name }}"
  register: vm_info_result
  delegate_to: localhost

- name: Set VM MoID fact
  set_fact:
    vm_moid: "{{ vm_info_result.virtual_machines[0].moid }}"
  delegate_to: localhost


- name: Perform System updates
  community.vmware.vmware_vm_shell:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    vm_id: "{{ vm_name }}"
    vm_username: 'root'
    vm_password: "{{ initial_root_password }}"
    vm_shell: /bin/bash
    vm_shell_args: "-c 'dnf update -y & echo $! | sed \"s/\\[1\\] //\"'"
  delegate_to: localhost
  when: patch_os | default(false) | bool
  register: updates_result

- name: Debug update start result
  debug:
    var: updates_result
  when: patch_os | default(false) | bool

- name: Extract PID of update process
  set_fact:
    update_pid: "{{ updates_result.msg }}"
  when: patch_os | default(false) | bool

- name: Debug extracted PID
  debug:
    var: update_pid
  when: patch_os | default(false) | bool

- name: Wait for update process to complete
  community.vmware.vmware_vm_shell:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    vm_id: "{{ vm_name }}"
    vm_username: 'root'
    vm_password: "{{ initial_root_password }}"
    vm_shell: /bin/bash
    vm_shell_args: "-c 'while kill -0 {{ update_pid }} 2>/dev/null; do sleep 10; done; echo 1'"
  delegate_to: localhost
  retries: 2
  delay: 300
  register: update_completion
  when: patch_os | default(false) | bool

- name: Debug update completion result
  debug:
    var: update_completion
  when: patch_os | default(false) | bool

- name: Set fact for update completion
  set_fact:
    update_completed: "{{ update_completion.changed }}"
  when: patch_os | default(false) | bool

- name: Check if reboot is required
  community.vmware.vmware_vm_shell:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    vm_id: "{{ vm_name }}"
    vm_username: 'root'
    vm_password: "{{ initial_root_password }}"
    vm_shell: /bin/bash
    vm_shell_args: "-c 'if [ -f /var/run/reboot-required ] || [ -f /usr/bin/needs-restarting ]; then echo 1; else echo 0; fi'"
  delegate_to: localhost
  register: reboot_status
  when: patch_os | default(false) | bool

- name: Debug reboot status
  debug:
    var: reboot_status
  when: patch_os | default(false) | bool

- name: Set fact for reboot required
  set_fact:
    reboot_required: "{{ reboot_status.changed }}"
  when: patch_os | default(false) | bool


- name: Change root password
  community.vmware.vmware_vm_shell:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    vm_id: "{{ vm_name }}"
    vm_username: 'root'
    vm_password: "{{ initial_root_password }}"
    vm_shell: /bin/bash
    vm_shell_args: "-c 'echo root:{{ new_root_password }} | chpasswd'"
  delegate_to: localhost
  when: vm_creation_result is changed

- name: Reboot if required
  community.vmware.vmware_guest_powerstate:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    name: "{{ vm_name }}"
    state: reboot-guest
  delegate_to: localhost
  when: 
    - patch_os | default(false) | bool
    - update_completed | bool
    - reboot_required | bool
  register: reboot_result
    
- name: Wait for VM power state (powered on)
  community.vmware.vmware_guest_powerstate:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    name: "{{ vm_name }}"
    state: powered-on
  delegate_to: localhost
  register: vm_power_state
  until: vm_power_state.instance.hw_power_status == 'poweredOn'
  retries: 30
  delay: 10
  when: 
    - patch_os | default(false) | bool
    - reboot_result is changed


- name: Wait for VMware tools to become available
  community.vmware.vmware_guest_tools_wait:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    name: "{{ vm_name }}"
  delegate_to: localhost
  when: 
    - patch_os | default(false) | bool
    - reboot_result is changed
    

- name: Wait for VM to get an IP address after reboot
  community.vmware.vmware_guest_info:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ datacenter_name }}"
    validate_certs: no
    name: "{{ vm_name }}"
  delegate_to: localhost
  register: vm_info_after_reboot
  until: vm_info_after_reboot.instance.ipv4 is defined and vm_info_after_reboot.instance.ipv4 != None and vm_info_after_reboot.instance.ipv4 != ""
  retries: 10
  delay: 6
  when:
    - patch_os | default(false) | bool
    
    

- name: Display VM IP address
  debug:
    msg: "The IP address of {{ vm_name }} is {{ vm_info_after_reboot.instance.ipv4 }}"
  when: 
    - vm_info_after_reboot.instance.ipv4 is defined and vm_info_after_reboot.instance.ipv4 != None and vm_info_after_reboot.instance.ipv4 != ""

- name: Update VMware vCenter inventory source
  awx.awx.inventory_source_update:
    name: "{{ awx_inventory_source_name | default('VMware vCenter') }}"
    inventory: "{{ vmware_inventory_id }}"
    organization: "{{ awx_organization_name | default('Default') }}"
    tower_host: "{{ awx_tower_url }}"
    tower_username: "{{ awx_username }}"
    tower_password: "{{ awx_password }}"
    validate_certs: false
  delegate_to: localhost
  register: inventory_update_result
  when: vmware_inventory_id is defined
  ignore_errors: true

- name: Display initial inventory update result
  debug:
    var: inventory_update_result

#- name: Wait for inventory update to complete
#  uri:
#    url: "https://{{ awx_tower_url }}/api/v2/jobs/{{ inventory_update_result.id }}/"
#    method: GET
#    user: "{{ awx_username }}"
#    password: "{{ awx_password }}"
#    force_basic_auth: yes
#    validate_certs: no
#    return_content: yes
#  register: job_result
#  until: job_result is success and job_result.json is defined and job_result.json.status not in ['pending', 'waiting', 'running']
#  retries: 60
#  delay: 10
#  ignore_errors: yes

- name: Display job result details
  debug:
    var: job_result

- name: Check inventory update result
  fail:
    msg: >
      Inventory update failed or timed out. 
      Status: {{ job_result.json.status | default('Unknown') if job_result.json is defined else 'API call failed' }}
      Error details: {{ job_result.msg | default('No error message') if job_result.failed else 'No error' }}
  when: job_result is failed or job_result.json is not defined or job_result.json.status != 'successful'

- name: Report successful inventory update
  debug:
    msg: "Inventory update completed successfully"
  when: job_result is success and job_result.json is defined and job_result.json.status == 'successful'