---
- name: Make sure requirements are met to run vmware modules PyVmoi and PyVim
  ansible.builtin.pip:
    name:
      - PyVmomi
      - PyVim
    state: present
  delegate_to: localhost

- name: Generate random hostname
  ansible.builtin.set_fact:
    random_hostname: "host{{ lookup('community.general.random_string', length=6, chars=['ascii_lowercase', 'digits']) }}"
    domain: "itmco.local"

- name: Set FQDN
  ansible.builtin.set_fact:
    fqdn: "{{ random_hostname }}.{{ domain }}"

- name: Create a virtual machine with customization and DHCP
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    datacenter: "{{ datacenter_name }}"
    cluster: "{{ cluster_name }}"
    name: "{{ vm_name }}"
    template: "{{ 'RH8' if version == '8' else 'RH9' }}"
    folder: "{{ vm_folder }}"
    state: "poweredon"
    customization:
      domain: "{{ domain }}"
      hostname: "{{ random_hostname }}"
    networks:
      - name: "{{ vm_network_name }}"
        device_type: vmxnet3
        connected: true
        start_connected: true
    wait_for_ip_address: true
  delegate_to: localhost
  register: vm_creation_result
  

- name: Get VM MoID
  community.vmware.vmware_vm_info:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    vm_name: "{{ vm_name }}"
  register: vm_info_result
  delegate_to: localhost

- name: Set VM MoID fact
  set_fact:
    vm_moid: "{{ vm_info_result.virtual_machines[0].moid }}"
  delegate_to: localhost

- name: Wait for VMware tools to become available by MoID
  community.vmware.vmware_guest_tools_wait:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    moid: "{{ vm_moid }}"
  delegate_to: localhost
  register: facts

- name: Check current system update status
  community.vmware.vmware_vm_shell:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    datacenter: "{{ datacenter_name }}"
    cluster: "{{ cluster_name }}"
    folder: "{{ vm_folder }}"
    vm_id: "{{ vm_name }}"
    vm_username: 'root'
    vm_password: "{{ initial_root_password }}"
    vm_shell: /bin/bash
    vm_shell_args: "-c 'dnf check-update; echo $?'"
  delegate_to: localhost
  register: update_check
  ignore_errors: yes

- name: Debug update check result
  debug:
    var: update_check
  when: patch_os | default(false) | bool

- name: Patching to latest version OS if updates available
  community.vmware.vmware_vm_shell:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    datacenter: "{{ datacenter_name }}"
    cluster: "{{ cluster_name }}"
    folder: "{{ vm_folder }}"
    vm_id: "{{ vm_name }}"
    vm_username: 'root'
    vm_password: "{{ initial_root_password }}"
    vm_shell: /bin/bash
    vm_shell_args: "-c 'dnf update -y; echo $?'"
  delegate_to: localhost
  when: 
    - patch_os | default(false) | bool
    - update_check.stdout | trim != "0"
  register: patching_result
  ignore_errors: yes

- name: Debug patching result
  debug:
    var: patching_result
  when: patch_os | default(false) | bool

- name: Verify system is up to date
  community.vmware.vmware_vm_shell:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    datacenter: "{{ datacenter_name }}"
    cluster: "{{ cluster_name }}"
    folder: "{{ vm_folder }}"
    vm_id: "{{ vm_name }}"
    vm_username: 'root'
    vm_password: "{{ initial_root_password }}"
    vm_shell: /bin/bash
    vm_shell_args: "-c 'dnf check-update; echo $?'"
  delegate_to: localhost
  register: final_update_check
  ignore_errors: yes

- name: Debug final update check
  debug:
    var: final_update_check
  when: patch_os | default(false) | bool

- name: Check final patching status
  fail:
    msg: "System is not fully up to date. Exit code: {{ final_update_check.stdout | trim }}"
  when: 
    - patch_os | default(false) | bool
    - final_update_check.stdout | trim not in ["0", "100"]


- name: Check kernel version
  community.vmware.vmware_vm_shell:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    datacenter: "{{ datacenter_name }}"
    cluster: "{{ cluster_name }}"
    folder: "{{ vm_folder }}"
    vm_id: "{{ vm_name }}"
    vm_username: 'root'
    vm_password: "{{ initial_root_password }}"
    vm_shell: /bin/bash
    vm_shell_args: "-c 'uname -r'"
  delegate_to: localhost
  register: kernel_version
  when: patch_os | default(false) | bool

- name: Change root password
  community.vmware.vmware_vm_shell:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    vm_id: "{{ vm_name }}"
    vm_username: 'root'
    vm_password: "{{ initial_root_password }}"
    vm_shell: /bin/bash
    vm_shell_args: "-c 'echo root:{{ new_root_password }} | chpasswd'"
  delegate_to: localhost
  when: vm_creation_result is changed
  
- name: Reboot VM if kernel was updated
  community.vmware.vmware_guest_powerstate:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    name: "{{ vm_name }}"
    state: reboot-guest
  delegate_to: localhost
  when: 
    - patch_os | default(false) | bool
    - patching_result.changed
    - kernel_version.changed

- name: Wait for VM power state (powered on)
  community.vmware.vmware_guest_powerstate:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    name: "{{ vm_name }}"
    state: powered-on
  delegate_to: localhost
  register: vm_power_state
  until: vm_power_state.instance.hw_power_status == 'poweredOn'
  retries: 30
  delay: 10
  when: 
    - patch_os | default(false) | bool
    - patching_result.changed
    - kernel_version.changed

- name: Wait for VMware tools to become available
  community.vmware.vmware_guest_tools_wait:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    name: "{{ vm_name }}"
  delegate_to: localhost
  when: 
    - patch_os | default(false) | bool
    - patching_result.changed
    - kernel_version.changed

- name: Wait for VM to get an IP address
  community.vmware.vmware_guest_info:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ datacenter_name }}"
    validate_certs: no
    name: "{{ vm_name }}"
  delegate_to: localhost
  register: vm_info
  until: vm_info.instance.ipv4 is defined and vm_info.instance.ipv4 != None and vm_info.instance.ipv4 != ""
  retries: 10
  delay: 6
  when: 
    - patch_os | default(false) | bool
    - patching_result.changed
    - kernel_version.changed

- name: Display VM IP address
  debug:
    msg: "The IP address of {{ vm_name }} is {{ vm_info.instance.ipv4 }}"
  when: 
    - patch_os | default(false) | bool
    - patching_result.changed
    - kernel_version.changed
    - vm_info.instance.ipv4 is defined and vm_info.instance.ipv4 != None and vm_info.instance.ipv4 != ""


- name: Update VMware vCenter inventory source
  awx.awx.inventory_source_update:
    name: "{{ awx_inventory_source_name | default('VMware vCenter') }}"
    inventory: "{{ vmware_inventory_id }}"
    organization: "{{ awx_organization_name | default('Default') }}"
    tower_host: "{{ awx_tower_url }}"
    tower_username: "{{ awx_username }}"
    tower_password: "{{ awx_password }}"
    validate_certs: false
  delegate_to: localhost
  register: inventory_update_result
  when: vmware_inventory_id is defined
  ignore_errors: true

- name: Display inventory update result
  debug:
    var: inventory_update_result

- name: Wait for inventory update to complete
  awx.awx.job_wait:
    job_id: "{{ inventory_update_result.id }}"
  delegate_to: localhost
  when: inventory_update_result is changed and inventory_update_result is success

