---
- name: Check for yum
  ansible.builtin.command: which yum
  register: yum_check
  ignore_errors: yes

- name: Check for dnf
  ansible.builtin.command: which dnf
  register: dnf_check
  ignore_errors: yes

- name: Check for apt
  ansible.builtin.command: which apt
  register: apt_check
  ignore_errors: yes


- name: Check for pip
  ansible.builtin.command: which pip
  register: pip_check
  ignore_errors: yes

- name: Check for pip3
  ansible.builtin.command: which pip3
  register: pip3_check
  ignore_errors: yes

- name: Display results
  ansible.builtin.debug:
    msg: |
          yum present: {{ yum_check.rc == 0 }}
          dnf present: {{ dnf_check.rc == 0 }}
          apt present: {{ apt_check.rc == 0 }}
          pip present: {{ pip_check.rc == 0 }}
          pip3 present: {{ pip3_check.rc == 0 }}

- name: Get Python version
  ansible.builtin.command: python3 --version
  register: python_version

- name: Display Python version
  ansible.builtin.debug:
    var: python_version.stdout

- name: Install python3-aiohttp
  ansible.builtin.dnf:
    name: python3-aiohttp
    state: present
    update_cache: yes
  delegate_to: localhost
