---
# defaults file for soe_update
ansible_distribution: "RedHat"
satellite_url : "192.168.2.156"
ip_address: "192.168.2.33"
ip_netmask: "255.255.255.0"
ip_gateway: "192.168.2.1"
dns1: "192.168.2.1"
dns2: "192.168.2.1"
vcenter_username: "Administrator@itmco.local"
vcenter_password: ""
vcenter_hostname: "vcenter.itmco.local"
template_name: "Client"
cluster_name: "ITMCO"
datacenter_name: "Datacenter"
domain_name: "itmco.local"
#vm_name: "{{ template_name }}-build"
vm_network_name: "DSwitch-VM Network"
vm_folder: "/vm/AAP_HOSTS"
ansible_python_interpreter: "/usr/bin/python3"
ansible_connection: "local"
awx_user: "{{ lookup('env', 'AWX_USER') }}"  # This will be set by AWX
vmware_inventory_id: 2
awx_tower_url: awx-dev-awx.apps.okd.itmco.local
