# roles/vm_remove/tasks/main.yml

---
- name: Make sure requirements are met to run vmware modules PyVmomi and PyVim
  ansible.builtin.pip:
    name:
      - PyVmomi
      - PyVim
    state: present
  delegate_to: localhost

- name: Get VM info
  community.vmware.vmware_guest_info:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: "{{ datacenter_name }}"
    validate_certs: no
    name: "{{ vm_name }}"
  delegate_to: localhost
  register: vm_info
  ignore_errors: yes

- name: Display VM details
  debug:
    msg: "VM {{ vm_name }} details: {{ vm_info.instance | default('VM not found') }}"
  when: vm_info.instance is defined

- name: Remove virtual machine
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    name: "{{ vm_name }}"
    state: absent
    force: yes
  delegate_to: localhost
  when: 
    - vm_info.instance is defined
    - confirm_removal | bool


- name: VM removal status
  debug:
    msg: >
      {% if vm_info.instance is not defined %}
        VM {{ vm_name }} does not exist.
      {% elif confirm_removal | bool %}
        VM {{ vm_name }} has been removed successfully.
      {% else %}
        VM removal was not confirmed. VM {{ vm_name }} still exists.
      {% endif %}
######
 name: Look up inventory IDs
  set_fact:
    inventories: "{{ lookup('awx.awx.controller_api', 'inventories', host=awx_tower_url, username=awx_username, password=awx_password, verify_ssl=false) }}"

- name: Display inventory information
  debug:
    msg: "Inventory Name: {{ item.name }}, ID: {{ item.id }}, Organization: {{ item.organization }}"
  loop: "{{ inventories.results }}"
  when: inventories.results is defined

- name: Set fact for Vmware inventory ID
  set_fact:
    vmware_inventory_id: "{{ item.id }}"
  loop: "{{ inventories.results }}"
  when: item.name == 'Vmware'

- name: Display Vmware inventory ID
  debug:
    var: vmware_inventory_id
  when: vmware_inventory_id is defined
######

- name: Update VMware vCenter inventory source
  awx.awx.inventory_source_update:
    name: "VMware vCenter"
    inventory: "{{ vmware_inventory_id }}"
    organization: "Tash"  # The organization name
    tower_host: "https://awx-awx.apps.okd.itmco.local"  #  AWX host URL
    tower_username: "{{ awx_username }}"  # Use a variable for the username
    tower_password: "{{ awx_password }}"  # Use a variable for the password
    validate_certs: no  # Set to 'no' if using self-signed certs
  delegate_to: localhost
  register: inventory_update_result

- name: Wait for inventory update to complete
  awx.awx.job_wait:
    job_id: "{{ inventory_update_result.id }}"
  delegate_to: localhost
  when: inventory_update_result is changed


